# Generated by Django 4.1.3 on 2023-04-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0002_alter_clubs_balance_alter_studentaccounts_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
