# Generated by Django 4.1.3 on 2023-04-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0003_alter_clubs_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccounts',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
