# Generated by Django 4.1.3 on 2023-05-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0004_alter_studentaccounts_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
    ]
