# Generated by Django 4.1.3 on 2023-05-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0005_clubs_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccounts',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
    ]
