# Generated by Django 4.1.3 on 2023-03-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('film_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('screen_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('showing_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('available_seats', models.IntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaManager.film')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaManager.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_paid', models.BooleanField()),
                ('students_tickets', models.IntegerField()),
                ('adults_tickets', models.IntegerField()),
                ('clubs_tickets', models.IntegerField()),
                ('total', models.IntegerField()),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaManager.showing')),
            ],
        ),
    ]
