# Generated by Django 4.1.3 on 2023-03-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='age_rating',
            field=models.CharField(default='Not Rated', max_length=100),
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
