# Generated by Django 4.1.3 on 2023-03-23 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaManager', '0003_film_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showing',
            name='screen',
        ),
        migrations.AddField(
            model_name='screen',
            name='no_seats',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
    ]
