# Generated by Django 4.1.3 on 2023-03-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaManager', '0004_remove_showing_screen_screen_no_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
