services:
  group_14:
    build: .
    entrypoint: ["./django-app-entrypoint.sh"]
    container_name: group_14
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - postgres-db


  postgres-db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: group-14-db
      POSTGRES_PASSWORD: postgres

volumes:
  db: