services:
  fe:
    build: ./fe
    entrypoint: ["./django-app-entrypoint.sh"]
    container_name: fe
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./fe:/app
    depends_on:
      - postgres-db
  
  services:
    build: ./services
    # command: python manage.py runserver 0.0.0.0:8001
    container_name: services
    entrypoint: ["./django-app-entrypoint-services.sh"]
    restart: unless-stopped
    volumes:
      - ./web_services:/app2
    ports:
      - "8001:8001"


  postgres-db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: group-14-db
      POSTGRES_PASSWORD: postgres

volumes:
  db: