services:
  fe:
    build: ./fe
    entrypoint: ["./django-app-entrypoint.sh"]
    container_name: fe
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./fe:/app
  
  web_services:
    build: ./web_services
    command: python manage.py runserver 0.0.0.0:8001
    container_name: web_services
    restart: unless-stopped
    volumes:
      - ./web_services:/app2
    ports:
      - "8001:8001"
    depends_on:
      - postgres-db


  postgres-db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: group-14-db
      POSTGRES_PASSWORD: postgres

volumes:
  db: