# Generated by Django 4.1.3 on 2023-03-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentaccounts',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
