# Generated by Django 4.1.3 on 2023-03-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaManager', '0002_film_age_rating_film_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
