# Generated by Django 4.1.3 on 2023-03-23 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaManager', '0005_screen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='screen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinemaManager.screen'),
            preserve_default=False,
        ),
    ]
