# Generated by Django 4.1.3 on 2023-04-06 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaManager', '0006_showing_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='screen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaManager.screen'),
        ),
    ]
