# Generated by Django 4.1.5 on 2023-04-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaManager', '0007_alter_showing_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='social_distancing',
            field=models.BooleanField(default=False),
        ),
    ]
