# Generated by Django 4.1.3 on 2023-05-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaManager', '0008_remove_booking_adults_tickets_booking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbooking',
            name='children_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
