# Generated by Django 4.1.3 on 2023-05-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaManager', '0009_guestbooking_children_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_distancing', models.BooleanField(default=False)),
            ],
        ),
    ]
